In [1]:
import numpy as np

In [15]:
def projection_matrix(basis_matrix):
    B = basis_matrix
    proj_m = B @ np.linalg.pinv(B.T @ B) @ B.T
    return proj_m

In [33]:
def vector_projected(basis_matrix, x):
    p = projection_matrix(basis_matrix) @ x
    return p

In [70]:
def lambdas(A, x):
    lambda_v = np.linalg.pinv(B.T @ B) @ B.T @ x
    return lambda_v

In [71]:
def check_symmetric(A):
    return np.allclose(A, A.T)

In [72]:
def check_rank(A):
    return np.linalg.matrix_rank(A)

In [81]:
array = [[1,1,1],[0,1,2]]
v = [12,0,0]

In [82]:
x = np.array(v).reshape(-1, 1)
B = np.array(array).T

A = projection_matrix(B)
p = vector_projected(B, x).reshape(-1, 1)
s = check_symmetric(A)
r = check_rank(A)
lambda_v = lambdas(A, x)

print(f'lambda vector: \n{lambda_v}')
print(f'projection matrix: \n{A}')
print(f'vector after projection: \n{p}')
print(f'projection matrix symmetric: {s}')
print(f'projection matrix rank: {r}')

lambda vector: 
[[10.]
 [-6.]]
projection matrix: 
[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]
vector after projection: 
[[10.]
 [ 4.]
 [-2.]]
projection matrix symmetric: True
projection matrix rank: 2
